#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo ' Styling, testing and building your project before committing'

# Check prettier
npm run check-format || 
(
    echo 'Prettier check failed. Run npm run format, add changes and try commit again';
    false;
)

# Check ESLint
npm run check-lint ||
(
    echo 'ESLint check failed. Make the required changes listed above, add changes and try to commit again';
    false;
)

# Check tsconfig
npm run check-types ||
(
    echo 'TypeScript type check failed. Make the changes required above, add changes and try to commit again';
    false;
)

npm run build || 
(
    echo 'Build failed!';
    false;
)

echo "Success commite"